version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto11
        commands:
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 608327197546.dkr.ecr.us-east-1.amazonaws.com

    build:
        commands:
            - mvn clean install
            - echo Maven Installed
            - docker build -t moviebookingwebapp .
            - docker tag moviebookingwebapp:latest 608327197546.dkr.ecr.us-east-1.amazonaws.com/moviebookingwebapp:latest
            - docker push 608327197546.dkr.ecr.us-east-1.amazonaws.com/moviebookingwebapp:latest

    post_build:
        commands:
            - echo Build completed on `date`